[workspace]
members = [".", "changelog_document", "commit_parser"]


[package]
name = "changelog"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
indexmap = { version = "2", features = ["serde"] }
anyhow.workspace = true
# regex = "1"
serde.workspace = true
serde_json = "1"
reqwest = { version = "0.12", features = ["blocking"] }
changelog = { path = "./changelog_document", package = "changelog_document" }
commit_parser = { path = "./commit_parser" }

[workspace.dependencies]
pom = { version = "3", features = ["trace"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
# thiserror = "1"
