[workspace]
members = [".", "changelog_document", "commit_parser"]


[package]
name = "changelog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5", features = ["derive"] }
indexmap = { version = "2", features = ["serde"] }
light_enum = "0.2.2"
log = "0.4.22"
memchr = "2.7.4"
pulldown-cmark = "0.11.0"
regex = "1.10.5"
serde_json = "1"
serde = { version = "1", features = ["derive"] }


[workspace.dependencies]
pom = { version = "3", features = ["trace"] }
# [dependencies.parse-changelog]
# path = "../parse-changelog"
# version = "0.6.8"
