name: Changelog Generation

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "CHANGELOG.md"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always
  RUST_LOG: "warn,changelog_gen=debug"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          # needed to disable generation when the changelog was modified
          fetch-depth: 2
      - uses: Swatinem/rust-cache@v2

      - run: |
          cargo run --locked -- generate

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(changelog): automatic changelog generation (skip changelog)"
