name: Changelog Test Generation

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - "CHANGELOG.md"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: changelog-gen
          
      - run: |
          changelog-gen generate --owner wiiznokes --repo changelog
          cat CHANGELOG.md

   
