name: Changelog Test Generation

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - "CHANGELOG.md"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always
  RUST_LOG: "warn,changelog_gen=debug"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: |
          cargo run -- generate --owner wiiznokes --repo changelog
          cat CHANGELOG.md
          env

   
