name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "[0-9]+.*"

  workflow_dispatch:
    inputs:
      tag:
        description: "Tag in the format X.Y.Z"
        required: true
        type: string
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Get the tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - run: echo ${{ github.ref_name }}

      - name: Print the tag name
        run: echo "The tag is ${{ env.TAG_NAME }}" 

      - uses: Swatinem/rust-cache@v2

      - if: ${{ github.event.inputs.tag != '' }}
        run: |
          git tag ${{ github.event.inputs.tag }} || true
          git push origin --tags || true
          # https://github.com/actions/checkout/issues/1467
          git fetch --tags || true

      - run: |
          git tag
          cargo run --locked -- generate --exclude-unidentified
          cargo run --locked -- release --stdout > CHANGELOG2.md
          diff CHANGELOG.md CHANGELOG2.md || true


      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(changelog): automatic release generation (skip changelog) [skip ci]"

      - run: |
          cargo run --locked -- show
