name: Release2


on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag in the format X.Y.Z"
        required: true
        type: string
  push:
    tags:
      - "[0-9]+.*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - if: ${{ github.ref_name != '' }}
        run: echo Using pushed tag ${{ github.ref_name }}

      - if: ${{ github.event.inputs.tag != '' }}
        run: |
          git tag ${{ github.event.inputs.tag }} || true
          git push origin --tags || true
          # https://github.com/actions/checkout/issues/1467
          git fetch --tags || true
          echo Using given tag ${{ github.event.inputs.tag }}

      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo run --locked -- generate --exclude-unidentified
          cargo run --locked -- release

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Automatic release PR"
          base: expe-declaer
          branch: changelog-release
          commit-message: "chore(changelog): automatic release generation (skip changelog) [skip ci]"
          delete-branch: true
          branch-suffix: short-commit-hash

      - run: |
          cargo run --locked -- show
