name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag in the format vX.Y.Z"
        required: true
        type: string
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - uses: Swatinem/rust-cache@v2
      - run: |
          git tag ${{ github.event.inputs.tag }} || true
          git push origin --tags || true
          # https://github.com/actions/checkout/issues/1467
          git fetch --tags
          cargo run --locked -- release
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(changelog): automatic release generation (skip changelog)"

      - run: |
          cargo run --locked -- show > RELEASE_CHANGELOG.md

      - uses: taiki-e/create-gh-release-action@v1
        with:
          # currently cause problem because the file is parsed
          #changelog: RELEASE_CHANGELOG.md
          ref: refs/tags/${{ github.event.inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: changelog-gen
          ref: refs/tags/${{ github.event.inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
